Resources:
  $forEach:
    iterator: "${self:custom.rate}"
    template:
      RateSchedule$forEach.value:
        Type: AWS::Events::Rule
        Properties:
          ScheduleExpression: rate(5 minutes)
          Targets:
            - Input: '{"scheduler":"$forEach.value"}'
              Arn: arn:aws:lambda:eu-central-1:123456789:function:callIt
              Id: callItId